# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
# IP: The module: 'DCM_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
# IP: The module: 'DCM_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab3_IPCore/vivado/IPCore.gen/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
